### ISSUE TITLE
GNOME 3.16 won't use metacity themes anymore

### ISSUE THREAD

**Issue by isacdaavid** [chpii/Headerbar#10]
I have tested GNOME Shell 3.15 rc and the window tip with rounded corners is not showing.
Reading https://blogs.gnome.org/fmuellner/2015/01/30/a-small-note-on-window-decorations/  makes me think that HTile will need a new kind of tweak.

**Comment by chpii** [comment]
This will look even better, because it will be plain CSS, and work across all themes.

It will be something as simple as this: https://wiki.archlinux.org/index.php/GTK%2B#Client-side_decorations

Later.

**Comment by chpii** [comment]
This can be relevant parts:

https://git.gnome.org/browse/gtk+/tree/gtk/theme/Adwaita/gtk-contained.css#n4394

**Comment by chpii** [comment]
Thankfully GNOME developers did all the job, we don't need any new hacks outside of Firefox!
Check new userstyle in tutorial. Cya!

**Comment by isacdaavid** [comment]
Awesome and thanks
