### ISSUE TITLE
No round titelbar corners on 3.16.0

### ISSUE THREAD

**Issue by bsteindorf** [chpii/Headerbar#11]
Hello,

i followed the instructions for 3.16+ but the corners are not rounded (stylish style 3.16+ applied) 
![firefox-no-round-corners](https://cloud.githubusercontent.com/assets/313188/6881318/4361e7c6-d55a-11e4-8395-fad9c6466670.png)

regards,
Benedikt

**Comment by chpii** [comment]
There is a bug with enabling rounded corners: you can't resize with left clicking on right and bottom edges of Firefox window.

I disabled rounded corners by default for now, but you can uncomment relevant lines in userstyle if you want.

Also you can disable DarkWDec for borders to match light theme and do not suck as much.

**Comment by DoctorJellyface** [comment]
\* goes to uncomment the lines \*

Any idea what the problem might be?

**Comment by chpii** [comment]
Problem is in setting `-moz-appearance: none`

As workaround it is possible to write extension that adds resize handle inside of window corner and some visual indication like on this mockup:

![broken](https://cloud.githubusercontent.com/assets/7461424/6927474/5e7403b6-d7f6-11e4-867f-258898a79db9.png)

**Comment by chpii** [comment]
I updated userstyle, for now it turns gray window behind rounded toolbar.

![2015-04-08 02-17-59](https://cloud.githubusercontent.com/assets/7461424/7035827/8816f648-dd95-11e4-9387-d059c01217ff.png)

**Comment by DoctorJellyface** [comment]
Nice. Definitely better than before, though if you drag it from maximized to unmaximized, it will have boxy corners until you let it go.

**Comment by phikal** [comment]
Have there been any improvements with this issue?

**Comment by chpii** [comment]
@DoctorJellyface now corners are the same for both maximized and unmaximized state, so they don't have boxy corners when unmaximizing.

@phikal I consider this issue closed. Corners are now sort of rounded, even if not as pretty.

**Comment by phikal** [comment]
![screenshot from 2015-06-03 12-40-30](https://cloud.githubusercontent.com/assets/6370419/7958237/c5fc9f4c-09ed-11e5-81b0-347bff6b5e25.png)

Just want to make sure, it's not getting better than this then?

**Comment by chpii** [comment]
@phikal
:sob: :star2: You're correct. :star2: :sob:
