### ISSUE TITLE
Popovers should be lower

### ISSUE THREAD

**Issue by DoctorJellyface** [chpii/Headerbar#12]
As you see on this screenshot, the popovers are too far up:
![ff-header-bar-bug1](https://cloud.githubusercontent.com/assets/7472425/6918221/21548662-d7ac-11e4-8b34-1d4e1f43bf2e.png)

For comparison, this is how it looks in Gedit. See how the arrow barely touches the button:
![ff-header-bar-bug2](https://cloud.githubusercontent.com/assets/7472425/6918226/2c82e196-d7ac-11e4-967a-e386f2acf9eb.png)

Also the popovers should be lighter, now I come to think of it.

**Comment by chpii** [comment]
Copy this issue [here](https://github.com/gnome-integration-team/firefox-gnome/issues).

I just did tutorial, not actual theme :)

**Comment by DoctorJellyface** [comment]
Yeah, I know, I just thought the position is (or could) by set by the Stylish userstyle.

**Comment by chpii** [comment]
Popover is lower in userstyle now.
