### ISSUE TITLE
Instructions for elementary Freya

### ISSUE THREAD

**Issue by SunShiranui** [chpii/Headerbar#14]
I noticed there are some files for elementary Freya but I don't understand how to use them. Would it be possible to have some instructions for elementary Freya?

**Comment by chpii** [comment]
Difference is only in step 4 and 5.

![elementary](http://cs625422.vk.me/v625422893/8676/F2yww6Jr1K8.jpg)

In [step 4](https://github.com/chpii/Headerbar#step-4) you just need to copy `Freya` folder to your `~/.local/share/themes` folder.

You can do this with CLI command(if you have `wget` utility installed) or just press `Download ZIP` and copy `Freya` directory from the archive to `~/.local/share/themes` folder. Then enable this theme with `gsettings set org.gnome.desktop.wm.preferences theme "Freya"` command. Note that you need to use `Headerbar style for GNOME 3.14-` in [step 5](https://github.com/chpii/Headerbar#step-5)

Also you can skip step 4 altogether and use `Headerbar style for GNOME 3.16+` in [step 5](https://github.com/chpii/Headerbar#step-5) but this corners of Firefox window will not look as good.

**Comment by chpii** [comment]
For real elementary integration progress you can check https://github.com/zeeeeee/firefox-elementary/issues/9 but there is no progress unfortunately.

If there will be no further questions I can close this issue.

**Comment by SunShiranui** [comment]
Thanks for your answer!
