### ISSUE TITLE
Remove tab animation

### ISSUE THREAD

**Issue by dyskette** [chpii/Headerbar#15]
Due to the tab animation from Firefox, when closing the last tab it lasts a few seconds to be really closed. This is more noticeable when playing some flash content on the last tab. Also this arrows appear while is closing.

![captura de pantalla de 2015-04-25 11-19-44](https://cloud.githubusercontent.com/assets/6687927/7333664/5fe318a4-eb3d-11e4-81d4-5e244c2bdb4f.png)

Changing `browser.tabs.animate` to `false` in `about:config` makes closing the last tab instantly.

**Comment by DoctorJellyface** [comment]
Nice trick, thanks.

**Comment by chpii** [comment]
@dyskette, included that info in tutorial, thank you.
