### ISSUE TITLE
Add new tab tools to the tutorial

### ISSUE THREAD

**Issue by DoctorJellyface** [chpii/Headerbar#16]
[New tab tools](https://addons.mozilla.org/en-US/firefox/addon/new-tab-tools/) is kinda a cool addon. With it I was able to achieve this effect:

![snimka obrazovky z 2015-06-03 16-05-16](https://cloud.githubusercontent.com/assets/7472425/7961895/a2b7e8da-0a0a-11e5-960c-d5d0b0271ce9.png)

My settings are something like this:

* background colour: `#F6F6F4`
* light theme
* 3 rows, 5 columns
* grid margin, spacing large
* launcher: do not show
* tile title size medium
* recently closed tabs off
* pin and remove buttons on
* site icons on
* whole thumbnails off

**Comment by chpii** [comment]
Thanks, will add that later.

You can remove *Australis menu List view* userstyle now from your Firefox that is causing back-forward icons to disappear - proper code for this is already included in main userstyle.

**Comment by DoctorJellyface** [comment]
Thanks, wasn't aware of that!

**Comment by DoctorJellyface** [comment]
Status?

**Comment by DoctorJellyface** [comment]
Haha, thanks.

**Comment by chpii** [comment]
@DoctorJellyface, feel free to make any changes you want :)

**Comment by chpii** [comment]
Tutorial has a lot of extensions already. It has to shrink down.

I do agree we need to make it look properly, but new tab tools is overkill.

Marked as invalid and closing, but can be reopened as another issue.

**Comment by DoctorJellyface** [comment]
Can't it have a bonus section?

**Comment by chpii** [comment]
We can style default new tab page.

But if there is more to this extension that helps to make it look more GNOME, it can have a mention.

**Comment by DoctorJellyface** [comment]
> We can style default new tab page.

Why didn't you say this before?

And yeah, New tab tools can do a lot of stuff, it's actually featured now by Mozilla.
