### ISSUE TITLE
Headerbar becomes too large

### ISSUE THREAD

**Issue by 183amir** [chpii/Headerbar#17]
After I apply the style in Gnome 3.16, the headerbar becomes much larger compared to other apps. I am using the default Adwaita theme. As you can see in the image below. On left there is Firefox and right is Nautilus.
![screenshot from 2015-06-04 20-17-07](https://cloud.githubusercontent.com/assets/5738695/7982956/b4a819c4-0af6-11e5-92b6-2f427522116c.png)

**Comment by DoctorJellyface** [comment]
It fits perfectly for me. What's your resolution?

**Comment by 183amir** [comment]
I'm sorry, this happens when I enable hidpi settings, `layout.css.devPixelsPerPx`, in firefox. Otherwise it looks fine. Could you please tell me how I can decrease the height?
