### ISSUE TITLE
List view userstyle 

### ISSUE THREAD

**Issue by 183amir** [chpii/Headerbar#18]
The List view userstyle  included in [here](https://userstyles.org/styles/96733/headerbar-style-for-gnome-3-16) is buggy with the add-ons that I use and I like the original menu style. Could you please remove this and provide it as a separate style?

**Comment by chpii** [comment]
Done, too bad you can't make use of it with your set of extensions.

Nevertheless, I separated it in another userstyle.

**Comment by 183amir** [comment]
Thank you.
