### ISSUE TITLE
Dark theme doesn't work

### ISSUE THREAD

**Issue by sryze** [chpii/Headerbar#24]
I followed the README instructions on [setting up the dark theme](https://github.com/chpii/Headerbar#dark-theme) but that didn't work for some reason. Any idea why? 

![screenshot from 2015-12-05 14-45-37](https://cloud.githubusercontent.com/assets/4525736/11606958/87baf508-9b56-11e5-9d68-419158627228.png)

![screenshot from 2015-12-05 14-46-30](https://cloud.githubusercontent.com/assets/4525736/11606964/9f44271c-9b56-11e5-87e7-6ab3a4f7df80.png)

Firefox version: Mozilla Firefox 42.0
GNOME Shell 3.16.4
Ubuntu 15.10

**Comment by seleznev** [comment]
GNOME Theme for Firefox [doesn't support this key anymore](https://github.com/gnome-integration-team/firefox-gnome/commit/bad4d7d65227a72d1da44fb13180ad69ec07ac47). You must have dark GTK+ theme to use dark variant.

**Comment by sryze** [comment]
I'm using Adwaita dark variant, should it work with it?

**Comment by seleznev** [comment]
> I'm using Adwaita dark variant, should it work with it?

Only if your Firefox built with GTK3. Mozilla planned to switch to GTK3 in Firefox 42, but something has gone wrong. So, you can to try GTK3 build by using Nightly build from [ftp.mozilla.org](http://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/).

The theme doesn't work perfect with Nightly, but you can check how it should works with GTK3...

![screenshot from 2015-12-05 15-29-53](https://cloud.githubusercontent.com/assets/1687481/11607140/2b74c146-9b5d-11e5-8256-ffd0aa9a41d0.png)

**Comment by sryze** [comment]
Well, the funny thing is, I have everything working perfectly with exactly the same version of Firefox on another system (Fedora 23), and I couldn't figure out what I was doing wrong. The only difference seems to be the version of GNOME - 3.16.4 vs .18.3 on the working system.

**Comment by seleznev** [comment]
> The only difference seems

You can open Browser console and paste following code:

```
Components.classes["@mozilla.org/xre/app-info;1"].getService(Components.interfaces.nsIXULRuntime).widgetToolkit;
```

Then you will see that toolkit uses in yours build of Firefox:

![screenshot from 2015-12-05 16-16-33](https://cloud.githubusercontent.com/assets/1687481/11607326/55f20338-9b63-11e5-9dfa-978a883ed405.png)

**Comment by sryze** [comment]
Sorry for the dumb question but how do you enable the input field there? Because mine doesn't have one...

**Comment by seleznev** [comment]
> Sorry for the dumb question but how do you enable the input field there? Because mine doesn't have one...

Ohh... I don't know. On my system I have it by default. :(

**Comment by sryze** [comment]
Installed GNOME 3.18.3 from GNOME staging PPA but had not luck, still the same light theme.

I actually ended up replacing Adwaita with a different theme ([Vertex](https://github.com/horst3180/Vertex-theme)). Firefox looks pretty good now, with a bonus of all other apps having a dark menubar as well. I"m loving it!

I think this can be closed for now.
