### ISSUE TITLE
Sticky tabs overlapped

### ISSUE THREAD

**Issue by netzgestaltung** [chpii/Headerbar#9]
hi - i followed the tutorial the first step, installed
- https://addons.mozilla.org/firefox/addon/gnotifier/
- https://launchpad.net/gnome-integration/firefox-gnome/firefox-gnome-releases/+download/gnome-firefox-35.1b1.xpi

and my sticky tabs are overlapping themeselves 
![bildschirmfoto von 2015-03-01 08 39 14](https://cloud.githubusercontent.com/assets/2329947/6429877/99c8264c-bfee-11e4-9c4d-cb83738fbee6.png)

**Comment by netzgestaltung** [comment]
After closing some tabs it disapeared - reopening tabs but its away - hope it will not come back

**Comment by johannesgunnar** [comment]
Pinned tabs seem to work fine for me with the tab stretch setting on.

**Comment by netzgestaltung** [comment]
im on ubuntu gnome 14.04.1 FF36 - Gnome 3.12.2
it was only temporary and it couldt be a conjunction with other addons - so seems everything ok.
